### ISSUE TITLE
ui checklist

### ISSUE THREAD

**Issue by jaanli** [rohanbansal12/ranking-featured-writing#1]
## design
- [ ] think about graying out text other than the title, soft color palette 
- [ ] solid line -- try to mimick twitter and google news and other lists of articles such as feedly in design
- [ ] think about mobile-friendly -- does react do this automatically? https://github.com/mui-org/material-ui
- [ ] send uri + robert the articles with the top values in each dimension across training + test articles, decide on 5 category names for the sliders. have one offbeat category like 'beef' hopefully
- [ ] i think for the demo we might want one sentence in about the same size font describing what this is and the relation to the demo paper (and link to the demo paper pdf)
- [ ] for the sliders: do percentiles make intuitive sense for the sliders? so it starts off in the middle, say at -3.05 for the dimension. then to the right it stops at e.g. the 99th percentile as it does on the left at the 1st percentile of values of that embedding. it seems like we'll have to play with it to see what scale is intuitive. 
- [ ] add source base url in parentheses

## features
- [ ] upload your own OPML file? seems like few would use this though

## end-to-end test
- [x] see if sliders change the values

## feedback
- [ ] uri
- [ ] robert
- [ ] toby

## tests 
- [ ] test on ipad
- [ ] test on android
- [x] test on windows
- [x] test on mac

## improvements
- [ ] infinite scrolling / load more button (clicking load more fetches 100 more links from lambda)
- [ ] https://material-ui.com/components/tables/ and other react components?
